apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ran-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ran-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: ran-operator
    namespace: ran-operator
