apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ran-operator
  name: ran-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ran-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: ran-operator