apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ran-operator
  name: ran-operator-role-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [ranoperator.example.com]
    resources: ["*"]
    verbs: [create, delete, get, list, watch,patch]

  # Application: other resources it produces and manipulates.
